site_name: TARDIS Connector
site_description: TARDIS Connector 2025 Workshop
repo_url: https://github.com/tardis-sn/connector25
site_author: TARDIS Connector

theme: 
  name: material

plugins:
  - mkdocstrings
  - mkdocs-jupyter

nav:
  - Home: index.md
  - Installation: installation.md
  - MESA to STIR: mesa_to_stir.md
  - STIR to STELLA: stir_to_stella.md
  - STELLA to TARDIS: stella_to_tardis.md
